#version 450
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_scalar_block_layout : require
#extension GL_GOOGLE_include_directive : require

#include "common.glsl"

layout (local_size_x = GROUP_SIZE, local_size_y = 1, local_size_z = 1) in;
void main() {
    uint id = gl_GlobalInvocationID.x;
    if(id >= pc.item_count)
        return;

    pc.input_items.data[id] = pc.sorted_items.data[id];
    pc.input_keys.data[id] = pc.sorted_keys.data[id];
}